# Generated by Django 5.0.6 on 2024-06-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJardineria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to='productos/'),
        ),
    ]
