# Generated by Django 5.0.6 on 2024-07-12 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJardineria', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
