# Generated by Django 5.0.6 on 2024-07-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJardineria', '0003_producto_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
